services:
  db:
    image: postgres:15
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: always
    ports:
      - "5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: . 
    restart: always
    command: bash -c "python manage.py collectstatic --no-input && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db 
    volumes:
      - .:/app

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: always

  channels:
    build: .
    command: bash -c "daphne unaa_leasing.asgi:application -b 0.0.0.0 -p 8001"
    restart: always
    env_file:
      - .env
    depends_on:
      - redis
      - app
    ports:
      - "8001:8001"
    volumes:
      - .:/app

volumes:
  pgdata:
  redis-data:
