# Generated by Django 4.2.18 on 2025-04-14 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalculateInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "down_payment",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Первоначальный взнос",
                    ),
                ),
                (
                    "leasing_term",
                    models.IntegerField(verbose_name="Срок лизинга (в месяцах)"),
                ),
                (
                    "interest_rate",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Процентная ставка"
                    ),
                ),
                (
                    "car_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Цена автомобиля"
                    ),
                ),
                (
                    "insurance_cost",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Стоимость страховки",
                    ),
                ),
                (
                    "gps_cost",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Стоимость GPS"
                    ),
                ),
                (
                    "decor_cost",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Стоимость оформления",
                    ),
                ),
            ],
            options={
                "verbose_name": "Информация для расчета",
                "verbose_name_plural": "Информация для расчетов",
            },
        ),
        migrations.CreateModel(
            name="ImagesCars",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="cars/", verbose_name="Изображение"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Изображение автомобиля",
                "verbose_name_plural": "Изображения автомобилей",
            },
        ),
        migrations.RemoveField(
            model_name="client",
            name="address",
        ),
        migrations.RemoveField(
            model_name="client",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="client",
            name="name",
        ),
        migrations.RemoveField(
            model_name="client",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="client",
            name="car_color",
            field=models.CharField(
                default=1, max_length=50, verbose_name="Цвет автомобиля"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="client",
            name="car_model",
            field=models.CharField(
                default=1, max_length=255, verbose_name="Модель автомобиля"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="client",
            name="car_name",
            field=models.CharField(
                default=1, max_length=255, verbose_name="Название автомобиля"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="client",
            name="car_number",
            field=models.CharField(
                default=1, max_length=50, verbose_name="Номер автомобиля"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="client",
            name="car_vin",
            field=models.CharField(default=1, max_length=50, verbose_name="VIN номер"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="client",
            name="car_year",
            field=models.IntegerField(default=1, verbose_name="Год автомобиля"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="client",
            name="fio",
            field=models.CharField(default=1, max_length=255, verbose_name="ФИО"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="client",
            name="whatsapp",
            field=models.CharField(default=1, max_length=50, verbose_name="WhatsApp"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="client",
            name="email",
            field=models.EmailField(max_length=255, verbose_name="Email"),
        ),
        migrations.CreateModel(
            name="RepaymentSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField(verbose_name="№")),
                ("due_date", models.DateField(verbose_name="Дата")),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Сумма лизинга / основного долга",
                    ),
                ),
                (
                    "main_debt",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Основной долг"
                    ),
                ),
                (
                    "interest",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Погашение начисл.",
                    ),
                ),
                (
                    "total_payment",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Итог к погашению"
                    ),
                ),
                ("is_paid", models.BooleanField(default=False, verbose_name="Оплачен")),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repayment_schedules",
                        to="core.client",
                        verbose_name="Клиент",
                    ),
                ),
            ],
            options={
                "verbose_name": "График погашения",
                "verbose_name_plural": "Графики погашения",
                "ordering": ["due_date"],
            },
        ),
        migrations.CreateModel(
            name="LocationClient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.FloatField(verbose_name="Широта")),
                ("longitude", models.FloatField(verbose_name="Долгота")),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="core.client",
                        verbose_name="Клиент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Локация клиента",
                "verbose_name_plural": "Локации клиентов",
            },
        ),
        migrations.CreateModel(
            name="InsuranceClient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "insurance_company",
                    models.CharField(
                        choices=[
                            ("OSAGO", "ОСАГО"),
                            ("KASKO", "КАСКО"),
                            ("OTHER", "ДРУГОЕ"),
                        ],
                        max_length=255,
                        verbose_name="Страховая компания",
                    ),
                ),
                (
                    "policy_number",
                    models.CharField(max_length=50, verbose_name="Номер полиса"),
                ),
                ("start_date", models.DateField(verbose_name="Дата начала")),
                ("end_date", models.DateField(verbose_name="Дата окончания")),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insurances",
                        to="core.client",
                        verbose_name="Клиент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Страхование клиента",
                "verbose_name_plural": "Страхования клиентов",
            },
        ),
        migrations.CreateModel(
            name="ContactClient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Имя")),
                ("phone", models.CharField(max_length=50, verbose_name="Телефон")),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="core.client",
                        verbose_name="Клиент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Контакт клиента",
                "verbose_name_plural": "Контакты клиентов",
            },
        ),
        migrations.CreateModel(
            name="AdCars",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "car_name",
                    models.CharField(
                        max_length=255, verbose_name="Название автомобиля"
                    ),
                ),
                (
                    "car_model",
                    models.CharField(max_length=255, verbose_name="Модель автомобиля"),
                ),
                ("car_year", models.IntegerField(verbose_name="Год автомобиля")),
                (
                    "car_color",
                    models.CharField(max_length=50, verbose_name="Цвет автомобиля"),
                ),
                ("car_vin", models.CharField(max_length=50, verbose_name="VIN номер")),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Цена"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                ("is_sold", models.BooleanField(default=False, verbose_name="Продано")),
                ("is_active", models.BooleanField(default=True, verbose_name="Срочно")),
                (
                    "images",
                    models.ManyToManyField(
                        blank=True,
                        related_name="ad_cars",
                        to="core.imagescars",
                        verbose_name="Изображения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Объявление о продаже",
                "verbose_name_plural": "Объявления о продаже",
            },
        ),
    ]
