# Generated by Django 4.2.18 on 2023-03-02 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_calculateinfo_imagescars_remove_client_address_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImagesAdCars",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="ad-cars/", verbose_name="Изображение"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Изображение автомобиля",
                "verbose_name_plural": "Изображения автомобилей",
            },
        ),
        migrations.CreateModel(
            name="ImagesClientCar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="cars/", verbose_name="Изображение"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images_client_car",
                        to="core.client",
                        verbose_name="Клиент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение автомобиля",
                "verbose_name_plural": "Изображения автомобилей",
            },
        ),
        migrations.RemoveField(
            model_name="adcars",
            name="images",
        ),
        migrations.RemoveField(
            model_name="calculateinfo",
            name="car_price",
        ),
        migrations.DeleteModel(
            name="ImagesCars",
        ),
        migrations.AddField(
            model_name="imagesadcars",
            name="ad_cars",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images_ad_cars",
                to="core.adcars",
                verbose_name="Объявление",
            ),
        ),
    ]
