# Generated by Django 4.2.18 on 2023-03-02 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_imagesadcars_imagesclientcar_remove_adcars_images_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="car_color",
        ),
        migrations.RemoveField(
            model_name="client",
            name="car_model",
        ),
        migrations.RemoveField(
            model_name="client",
            name="car_name",
        ),
        migrations.RemoveField(
            model_name="client",
            name="car_number",
        ),
        migrations.RemoveField(
            model_name="client",
            name="car_vin",
        ),
        migrations.RemoveField(
            model_name="client",
            name="car_year",
        ),
        migrations.RemoveField(
            model_name="imagesclientcar",
            name="client",
        ),
        migrations.CreateModel(
            name="ClientCar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "car_name",
                    models.CharField(
                        max_length=255, verbose_name="Название автомобиля"
                    ),
                ),
                (
                    "car_model",
                    models.CharField(max_length=255, verbose_name="Модель автомобиля"),
                ),
                ("car_year", models.IntegerField(verbose_name="Год автомобиля")),
                (
                    "car_color",
                    models.CharField(max_length=50, verbose_name="Цвет автомобиля"),
                ),
                ("car_vin", models.CharField(max_length=50, verbose_name="VIN номер")),
                (
                    "car_number",
                    models.CharField(max_length=50, verbose_name="Номер автомобиля"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_car",
                        to="core.client",
                        verbose_name="Клиент",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="imagesclientcar",
            name="client_car",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images_client_car",
                to="core.clientcar",
                verbose_name="Клиент",
            ),
            preserve_default=False,
        ),
    ]
