# Generated by Django 4.2.18 on 2025-04-15 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_remove_client_car_color_remove_client_car_model_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clientcar",
            options={
                "verbose_name": "Авто клиентов",
                "verbose_name_plural": "Авто клиентов",
            },
        ),
        migrations.RemoveField(
            model_name="repaymentschedule",
            name="client",
        ),
        migrations.RemoveField(
            model_name="repaymentschedule",
            name="number",
        ),
        migrations.AddField(
            model_name="repaymentschedule",
            name="car_client",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="repayment_schedules",
                to="core.clientcar",
                verbose_name="Авто клиента",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="repaymentschedule",
            name="overdue_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Просрочка",
            ),
        ),
        migrations.AddField(
            model_name="repaymentschedule",
            name="paid_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Погашено",
            ),
        ),
        migrations.AddField(
            model_name="repaymentschedule",
            name="paid_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата погашения"
            ),
        ),
        migrations.AddField(
            model_name="repaymentschedule",
            name="remaining_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Остаток к погашению",
            ),
        ),
        migrations.AlterField(
            model_name="adcars",
            name="car_vin",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="VIN номер"
            ),
        ),
        migrations.AlterField(
            model_name="adcars",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="adcars",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Цена",
            ),
        ),
        migrations.AlterField(
            model_name="calculateinfo",
            name="decor_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Стоимость оформления",
            ),
        ),
        migrations.AlterField(
            model_name="calculateinfo",
            name="down_payment",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Первоначальный взнос",
            ),
        ),
        migrations.AlterField(
            model_name="calculateinfo",
            name="gps_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Стоимость GPS",
            ),
        ),
        migrations.AlterField(
            model_name="calculateinfo",
            name="insurance_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Стоимость страховки",
            ),
        ),
        migrations.AlterField(
            model_name="calculateinfo",
            name="interest_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Процентная ставка",
            ),
        ),
        migrations.AlterField(
            model_name="calculateinfo",
            name="leasing_term",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Срок лизинга (в месяцах)"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="email",
            field=models.EmailField(
                blank=True, max_length=255, null=True, verbose_name="Email"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="phone",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Телефон"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="whatsapp",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="WhatsApp"
            ),
        ),
        migrations.AlterField(
            model_name="clientcar",
            name="car_color",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Цвет автомобиля"
            ),
        ),
        migrations.AlterField(
            model_name="clientcar",
            name="car_number",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Номер автомобиля"
            ),
        ),
        migrations.AlterField(
            model_name="clientcar",
            name="car_vin",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="VIN номер"
            ),
        ),
        migrations.AlterField(
            model_name="imagesadcars",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="ad-cars/", verbose_name="Изображение"
            ),
        ),
        migrations.AlterField(
            model_name="imagesclientcar",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="cars/", verbose_name="Изображение"
            ),
        ),
        migrations.AlterField(
            model_name="insuranceclient",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="insurances",
                to="core.clientcar",
                verbose_name="Клиент",
            ),
        ),
        migrations.AlterField(
            model_name="insuranceclient",
            name="insurance_company",
            field=models.CharField(
                choices=[("OSAGO", "ОСАГО"), ("KASKO", "КАСКО")],
                max_length=255,
                verbose_name="Страховая компания",
            ),
        ),
    ]
