# Generated by Django 4.2.18 on 2025-04-15 10:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_clientcar_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="repaymentschedule",
            options={
                "ordering": ["paid_date"],
                "verbose_name": "График погашения",
                "verbose_name_plural": "Графики погашения",
            },
        ),
        migrations.RemoveField(
            model_name="repaymentschedule",
            name="due_date",
        ),
    ]
