# Generated by Django 4.2.18 on 2025-04-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_alter_repaymentschedule_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="repaymentschedule",
            name="paid_amount",
        ),
        migrations.RemoveField(
            model_name="repaymentschedule",
            name="remaining_amount",
        ),
        migrations.AddField(
            model_name="clientcar",
            name="paid_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Погашено",
            ),
        ),
        migrations.AddField(
            model_name="clientcar",
            name="remaining_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Остаток к погашению",
            ),
        ),
        migrations.AddField(
            model_name="clientcar",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=1,
                max_digits=12,
                verbose_name="Сумма лизинга / основного долга",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="repaymentschedule",
            name="overdue_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Просрочки",
            ),
        ),
    ]
