# Generated by Django 4.2.18 on 2025-05-21 05:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_send_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactclient",
            name="phone",
            field=models.CharField(max_length=50, unique=True, verbose_name="Телефон"),
        ),
    ]
