# Generated by Django 4.2.18 on 2025-05-27 08:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_alter_contactclient_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientcar",
            name="client_guid",
            field=models.UUIDField(
                blank=True, null=True, unique=True, verbose_name="GUID клиента из 1С"
            ),
        ),
        migrations.AddField(
            model_name="clientcar",
            name="loan_guid",
            field=models.UUIDField(
                blank=True, null=True, unique=True, verbose_name="GUID кредита из 1С"
            ),
        ),
        migrations.AlterField(
            model_name="repaymentschedule",
            name="is_paid",
            field=models.CharField(
                choices=[
                    ("is_paid", "Оплачено"),
                    ("not_paid", "Не оплачено"),
                    ("in_process", "В ожидании"),
                ],
                verbose_name="Оплата",
            ),
        ),
    ]
