# Generated by Django 4.2.18 on 2025-05-27 10:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_clientcar_client_guid_clientcar_loan_guid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="repaymentschedule",
            name="interest",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Погашение начисл.",
            ),
        ),
        migrations.AlterField(
            model_name="repaymentschedule",
            name="main_debt",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Основной долг",
            ),
        ),
    ]
