# Generated by Django 4.2.18 on 2025-05-27 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_alter_repaymentschedule_interest_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="repaymentschedule",
            name="total_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Сумма лизинга / основного долга",
            ),
        ),
        migrations.AddConstraint(
            model_name="clientcar",
            constraint=models.UniqueConstraint(
                fields=("client_guid",), name="unique_client_guid"
            ),
        ),
        migrations.AddConstraint(
            model_name="clientcar",
            constraint=models.UniqueConstraint(
                fields=("loan_guid",), name="unique_loan_guid"
            ),
        ),
    ]
