# Generated by Django 4.2.18 on 2025-10-02 08:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="registration_address",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Регистрация"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="residence",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Место жительства"
            ),
        ),
        migrations.AddField(
            model_name="clientcar",
            name="advance_payment_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Авансовый платёж",
            ),
        ),
        migrations.AddField(
            model_name="clientcar",
            name="deal_number",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Номер сделки"
            ),
        ),
        migrations.AddField(
            model_name="clientcar",
            name="disbursement_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата выдачи лизинга"
            ),
        ),
        migrations.AddField(
            model_name="clientcar",
            name="due_amount_interest",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Просроченная сумма по процентам",
            ),
        ),
        migrations.AddField(
            model_name="clientcar",
            name="due_amount_principal",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Просроченная сумма по основному долгу",
            ),
        ),
        migrations.AddField(
            model_name="clientcar",
            name="due_days_interest",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Дней просрочки по процентам"
            ),
        ),
        migrations.AddField(
            model_name="clientcar",
            name="due_days_principal",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Дней просрочки по основному долгу"
            ),
        ),
        migrations.AddField(
            model_name="clientcar",
            name="interest_balance",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Остаток по процентам",
            ),
        ),
        migrations.AddField(
            model_name="clientcar",
            name="last_payment_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата последнего платежа"
            ),
        ),
        migrations.AddField(
            model_name="clientcar",
            name="principal_balance",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Остаток по основному долгу",
            ),
        ),
        migrations.AddField(
            model_name="clientcar",
            name="term",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Срок (в месяцах)"
            ),
        ),
        migrations.AddField(
            model_name="clientcar",
            name="и",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Остаток по пене",
            ),
        ),
    ]
