# Generated by Django 4.2.18 on 2025-04-14 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
        ("accounts", "0002_remove_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="core.client",
                verbose_name="Клиент",
            ),
        ),
    ]
