# Generated by Django 4.2.18 on 2025-05-29 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_user_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="expo_push_token",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Expo Push Token"
            ),
        ),
    ]
